# 0, 0
30=""

# 1, 0
48=""

# 2, 0
46=""

# 3, 0
32=""

# 4, 0
18="xdotool type 7"

# 5, 0
33="xdotool type 8"

# 6, 0
34="xdotool type 9"

# 7, 0
70="xdotool key Enter"

# 0, 1
35=""

# 1, 1
23=""

# 2, 1
36=""

# 3, 1
37=""

# 4, 1
69="xdotool type 4"

# 5, 1
98="xdotool type 5"

# 6, 1
55="xdotool type 6"

# 7, 1
74="xdotool type ."

# 0, 2
38=""

# 1, 2
50=""

# 2, 2
49=""

# 3, 2
24=""

# 4, 2
71="xdotool type 1"

# 5, 2
72="xdotool type 2"

# 6, 2
73="xdotool type 3"

# 7, 2
78="xdotool type 0"

# 0, 3
25="/run/current-system/sw/bin/brave http://localhost:3000 && sleep 0.1 && xdotool key Ctrl+Shift+i && xdotool key Ctrl+p && sleep 0.1 && xdotool key Ctrl+Shift+r"

# 1, 3
16="/run/current-system/sw/bin/brave https://staging.travelzap.com && sleep 0.1 && xdotool key Ctrl+Shift+i && sleep 0.1 && xdotool key Ctrl+Shift+r"

# 2, 3
19="/run/current-system/sw/bin/brave https://gitlab.com/destify-dev/odyssey/frontend"

# 3, 3
31="/run/current-system/sw/bin/brave https://3.basecamp.com/5705326/my/readings"

# 4, 3
75="xdotool key Super_L+ShiftL+1 && xdotool key Super_L+ShiftL+2 && xdotool key Super_L+ShiftL+3 && xdotool key Super_L+2"

# 5, 3
76="xdotool key Super_L+ShiftL+4 && xdotool key Super_L+ShiftL+5 && xdotool key Super_L+ShiftL+6 && xdotool key Super_L+5"

# 6, 3
77="xdotool key Super_L+ShiftL+7 && xdotool key Super_L+ShiftL+8 && xdotool key Super_L+ShiftL+9 && xdotool key Super_L+8"

# 7, 3
96="brave --profile-directory='Profile 3'"

# 0, 4
20="xdotool key Super_L+Shift_L+r"

# 1, 4
22="xdotool type 4"

# 2, 4
47="xdotool type 5"

# 3, 4
17="xdotool type 6"

# 4, 4
79=""

# 5, 4
80=""

# 6, 4
81=""

# 7, 4
82="brave --profile-directory='Default'"

# 0, 5
45="betterlockscreen --lock"

# 1, 5
21=""

# 2, 5
44=""

# 3, 5
83=""

# 4, 5
105="playerctl previous"

# 5, 5
106="playerctl play-pause"

# 6, 5
103="playerctl next"

# 7, 5
108="xdotool key Super_L+Enter"
